[[plugins]]
repo = "Shougo/ddu.vim"
depends = [
    "denops.vim",
]
hooks_file = "~/.config/nvim/hooks/ddu.lua"

# ui
[[plugins]]
repo = "Shougo/ddu-ui-ff"
[[plugins]]
repo = "Shougo/ddu-ui-filer"

# source
[[plugins]]
repo = "Shougo/ddu-source-file"
[[plugins]]
repo = "Shougo/ddu-source-file_rec"
[[plugins]]
repo = "uga-rosa/ddu-source-lsp"
[[plugins]]
repo = "shun/ddu-source-buffer"
[[plugins]]
repo = "matsui54/ddu-source-help"
[[plugins]]
repo = "shun/ddu-source-rg"

# filter
[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"
[[plugins]]
repo = "Shougo/ddu-filter-sorter_alpha"
[[plugins]]
repo = "yuki-yano/ddu-filter-fzf"

# kind
[[plugins]]
repo = "Shougo/ddu-kind-file"

# column
[[plugins]]
repo = "ryota2357/ddu-column-icon_filename"

# ------------------------------------------------

# filer
[[plugins]]
repo = "Shougo/ddu-ui-filer"
name = "ddu-tool-filer"
depends = [
    "ddu.vim",
    "ddu-source-file",
    "ddu-filter-sorter_alpha",
    "ddu-kind-file",
    "ddu-column-icon_filename"
]
on_map = { n = "<leader>e" }
hooks_file = "~/.config/nvim/hooks/filer.lua"

# fuzzy finder
[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-ff_file"
depends = [
    "ddu.vim",
    "ddu-source-file_rec",
    "ddu-filter-fzf",
    "ddu-kind-file",
]
on_map = { n = "<leader>ff" }
hooks_file = "~/.config/nvim/hooks/ff_file.lua"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-ff_grep"
depends = [
    "ddu.vim",
    "ddu-source-rg",
    "ddu-kind-file",
]
on_map = { n = "<leader>fg" }
hooks_file = "~/.config/nvim/hooks/ff_grep.lua"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-ff_buffer"
depends = [
    "ddu.vim",
    "ddu-source-buffer",
    "ddu-filter-fzf",
    "ddu-kind-file",
]
on_map = { n = "<leader>fb" }
hooks_file = "~/.config/nvim/hooks/ff_buffer.lua"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-ff_help"
depends = [
    "ddu.vim",
    "ddu-source-help",
    "ddu-filter-fzf",
]
on_map = { n = "<leader>fh" }
hooks_file = "~/.config/nvim/hooks/ff_help.lua"

# lsp
[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-lsp_definition"
depends = [
    "ddu.vim",
    "ddu-source-lsp",
]
on_map = { n = "<leader>ld" }
hooks_file = "~/.config/nvim/hooks/ff_lsp.lua"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-lsp_workspaceSymbol"
depends = [
    "ddu.vim",
    "ddu-source-lsp",
    "ddu-filter-fzf",
]
on_map = { n = "<leader>ls" }
hooks_file = "~/.config/nvim/hooks/ff_lsp.lua"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
name = "ddu-tool-lsp_diagnostic"
depends = [
    "ddu.vim",
    "ddu-source-lsp",
]
on_map = { n = "<leader>xx" }
hooks_file = "~/.config/nvim/hooks/ff_lsp.lua"
