[[plugins]]
repo = "Shougo/ddu.vim"
depends = [
    "denops.vim",
]
hooks_file = "~/.config/nvim/hooks/ddu.lua"

# ui
[[plugins]]
repo = "Shougo/ddu-ui-ff"
[[plugins]]
repo = "Shougo/ddu-ui-filer"

# filter
[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"
[[plugins]]
repo = "yuki-yano/ddu-filter-fzf"

# kind
[[plugins]]
repo = "Shougo/ddu-kind-file"

# column
[[plugins]]
repo = "ryota2357/ddu-column-icon_filename"

# filer
[[plugins]]
repo = "Shougo/ddu-source-file"
depends = [
    "ddu.vim",
    "ddu-ui-filer",
    "ddu-kind-file",
    "ddu-column-icon_filename"
]
on_map = { n = "<leader>e" }
hooks_file = "~/.config/nvim/hooks/filer.lua"

# fuzzy finder
[[plugins]]
repo = "Shougo/ddu-source-file_rec"
depends = [
    "ddu.vim",
    "ddu-ui-ff",
    "ddu-filter-fzf",
    "ddu-kind-file",
]
on_map = { n = "<leader>f" }
hooks_file = "~/.config/nvim/hooks/ff.lua"

# lsp
[[plugins]]
repo = "uga-rosa/ddu-source-lsp"
depends = [
    "ddu.vim",
    "ddu-ui-ff",
]
on_map = { n = "<leader>l" }
hooks_file = "~/.config/nvim/hooks/lsp.lua"
