[[plugins]]
repo = "nvim-tree/nvim-web-devicons"

[[plugins]]
repo = "windwp/nvim-autopairs"
on_event = "InsertEnter"
lua_source = '''
    require("nvim-autopairs").setup({
        check_ts = true,
    })
'''

[[plugins]]
repo = "hiphish/rainbow-delimiters.nvim"
on_event = ["BufNewFile", "BufReadPost"]

[[plugins]]
repo = "42paris/42header"
on_cmd = "Stdheader"
hook_add = '''
    let g:user42 = 'sota'
    let g:mail42 = 'sota@student.42tokyo.jp'
'''

[[plugins]]
repo = "folke/lazydev.nvim"
on_ft = "lua"
lua_source = '''
    require("lazydev").setup({})
'''

[[plugins]]
repo = "j-hui/fidget.nvim"
on_event = ["BufNewFile", "BufReadPost"]
lua_source = '''
    require("fidget").setup({})
'''

[[plugins]]
repo = "rebelot/heirline.nvim"
depends = [
    "nvim-web-devicons",
]
on_event = "UIEnter"
hooks_file = "~/.config/nvim/hooks/heirline.lua"

[[plugins]]
repo = "stevearc/conform.nvim"
hooks_file = "~/.config/nvim/hooks/conform.lua"
on_map = { n = "<leader>lf" }

[[plugins]]
repo = "kylechui/nvim-surround"
on_map = { n = ["ys", "cs", "ds"] }
lua_source = '''
    require("nvim-surround").setup({})
'''

[[plugins]]
repo = "norcalli/nvim-colorizer.lua"
on_event = ["BufNewFile", "BufReadPost"]
lua_source = '''
    require("colorizer").setup()
'''
