[[plugins]]
repo = "sainnhe/everforest"
hook_add = '''
    let g:everforest_background = 'hard'
    colorscheme everforest
'''

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
rev = "master"
hook_post_update = '''
    TSUpdateSync bash c cpp dockerfile git_config git_rebase gitignore json json5 lua make markdown markdown_inline python rust ssh_config tmux typescript vim vimdoc zig
'''
lua_source = '''
    require("nvim-treesitter.configs").setup({
        highlight = {
            enable = true,
        },
        indent = {
            enable = true,
        },
    })
'''

[[plugins]]
repo = "Shougo/ddc-source-lsp"
hooks_file = "~/.config/nvim/hooks/lsp.lua"

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "xiyaowong/transparent.nvim"

[[plugins]]
repo = "wakatime/vim-wakatime"
