[[plugins]]
repo = "sainnhe/everforest"
hook_add = '''
    let g:everforest_background = 'hard'
    colorscheme everforest
'''

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
rev = "master"
hook_post_update = '''
    TSUpdateSync bash c cpp dockerfile git_config git_rebase gitignore json json5 lua make markdown markdown_inline python rust ssh_config tmux typescript vim vimdoc zig
'''
lua_source = '''
    require("nvim-treesitter.configs").setup({
        highlight = {
            enable = true,
        },
        indent = {
            enable = true,
        },
    })
'''

[[plugins]]
repo = "Shougo/ddc-source-lsp"
hooks_file = "~/.config/nvim/hooks/lsp.lua"

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "xiyaowong/transparent.nvim"
lua_source = '''
    vim.api.nvim_set_hl(0, "NormalFloat", { fg = vim.api.nvim_get_hl(0, { name = "NormalFloat" }).fg, bg = nil })
    vim.api.nvim_set_hl(0, "FloatBorder", { fg = vim.api.nvim_get_hl(0, { name = "FloatBorder" }).fg, bg = nil })
    vim.api.nvim_set_hl(0, "FloatTitle", { fg = vim.api.nvim_get_hl(0, { name = "FloatTitle" }).fg, bg = nil })
'''

[[plugins]]
repo = "lewis6991/gitsigns.nvim"
lua_source = '''
    vim.api.nvim_set_hl(0, "GitSignsAddInline", { fg = nil, bg = "#003800" })
    vim.api.nvim_set_hl(0, "GitSignsChangeInline", { fg = nil, bg = "#404000" })
    vim.api.nvim_set_hl(0, "GitSignsDeleteInline", { fg = nil, bg = "#400000" })
    require("gitsigns").setup({
        signs = {
            add = { text = "┃+" },
            change = { text = "┃~" },
        },
        signs_staged = {
            add = { text = '┃+' },
            change = { text = "┃~" },
        },
        word_diff = true,
        numhl = true,
        current_line_blame = true,
    })
'''

[[plugins]]
repo = "folke/flash.nvim"
lua_source = '''
    require("flash").setup({})
    vim.keymap.set({ "n", "x", "o" }, "s", function() require("flash").jump() end, { noremap = true, silent = true, desc = "Flash" })
    vim.keymap.set({ "n", "x", "o" }, "S", function() require("flash").treesitter() end, { noremap = true, silent = true, desc = "Flash Treesitter" })
    vim.keymap.set("o", "r", function() require("flash").remote() end, { noremap = true, silent = true, desc = "Remote Flash" })
    vim.keymap.set({ "o", "x" }, "R", function() require("flash").treesitter_search() end, { noremap = true, silent = true, desc = "Flash Treesitter Search" })
'''

[[plugins]]
repo = "numToStr/Comment.nvim"
lua_source = '''
    require("Comment").setup()
'''
