[settings]
experimental = true
jobs = 4
lockfile = true

[tools]
bat = "latest"
btop = "latest"
chezmoi = "latest"
delta = "latest"
deno = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
"github:io12/pwninit" = { version = "3.3.1", asset_pattern = "pwninit" }
"github:llvm/llvm-project" = { version = "latest", version_prefix = "llvmorg-", asset_pattern = "LLVM-*-Linux-X64.tar.xz", bin_path = "LLVM-{version}-Linux-X64/bin" }
lsd = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
"npm:pyright" = "latest"
podman = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tmux = "3.5a"
uv = "latest"
zls = "latest"
zig = "latest"
