[settings]
experimental = true
jobs = 4
lockfile = true

[tools]
bat = "latest"
btop = "latest"
chezmoi = "latest"
"cargo:virtiofsd" = "latest"
delta = "latest"
deno = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
"github:containers/gvisor-tap-vsock" = { version = "latest", asset_pattern = "gvproxy-linux-amd64", rename_exe = "gvproxy" }
"github:containers/podman" = { version = "latest", asset_pattern = "podman-remote-static-linux_amd64.tar.gz", rename_exe = "podman" }
"github:io12/pwninit" = { version = "3.3.1", asset_pattern = "pwninit" }
"github:llvm/llvm-project" = { version = "latest", version_prefix = "llvmorg-", asset_pattern = "LLVM-*-Linux-X64.tar.xz", bin_path = "LLVM-{version}-Linux-X64/bin" }
lsd = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
"npm:pyright" = "latest"
"npm:@openai/codex" = "latest"
"pipx:podman-compose" = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tmux = "3.5a"
uv = "latest"
zls = "latest"
zig = "latest"
